Add doc for integrate feeabs module with new chain.
osmosis-labs/fee-abstraction pull request #148
Opened 2024-03-03 08:39 UTC by tnv1

2024-03-06 04:09 UTC, tropicaldog requested changes

2024-03-06 04:09 UTC, tropicaldog commented on tests/integration/cosmoshub/relayers/paths/query.json
> +      "version": "icq-1"
should be ics20-1

2024-03-06 04:11 UTC, tnv1 commented on tests/integration/cosmoshub/relayers/paths/query.json
> +      "version": "icq-1"
oh, thanks

2024-03-08 09:02 UTC, tropicaldog approved these changes

2024-03-08 14:11 UTC, merged